---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by buis_p.
--- DateTime: 30/08/2019 13:38
---

Locales['fr'] = {

    ['dirty_money'] = 'Argent sale: <span style="color: red;">$%s</span>',

}